# This is a basic workflow to help you get started with Actions

name: Production Build Front

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Use the node version specified in the strategy
      - name: Use node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Install packages
        run: |
          npm i
          
      - name: Production Build
        run: |
          unset CI
          npm run build
          
      - name: Deploy to S3 Server
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.REACT_APP_S3_BUCKET_REGION }}
          SOURCE_DIR: "build"
          REACT_APP_S3_BUCKET_NAME: ${{ secrets.REACT_APP_S3_BUCKET_NAME }}
          REACT_APP_S3_BUCKET_REGION: ${{ secrets.REACT_APP_S3_BUCKET_REGION }}
          REACT_APP_AWS_ACCESS_KEY_ID: ${{ secrets.REACT_APP_AWS_ACCESS_KEY_ID }}
          REACT_APP_AWS_SECRET_ACCESS_KEY: ${{ secrets.REACT_APP_AWS_SECRET_ACCESS_KEY }}
          REACT_APP_DYNAMO_DB_URL: ${{ secrets.REACT_APP_DYNAMO_DB_URL }}
          REACT_APP_S3_IMAGE_URL: ${{ secrets.REACT_APP_S3_IMAGE_URL }}

      
